//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.30 at 10:04:50 PM CEST 
//


package com.otkudznam.booking.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lodgings" type="{http://www.otkudznam.com/booking/model}Lodging" maxOccurs="unbounded"/>
 *         &lt;element name="imageUris" type="{http://www.otkudznam.com/booking/model}ImageUrl" maxOccurs="unbounded"/>
 *         &lt;element name="lodgingTypes" type="{http://www.otkudznam.com/booking/model}LodgingType" maxOccurs="unbounded"/>
 *         &lt;element name="categories" type="{http://www.otkudznam.com/booking/model}Category" maxOccurs="unbounded"/>
 *         &lt;element name="agents" type="{http://www.otkudznam.com/booking/model}Agent" maxOccurs="unbounded"/>
 *         &lt;element name="users" type="{http://www.otkudznam.com/booking/model}User" maxOccurs="unbounded"/>
 *         &lt;element name="comments" type="{http://www.otkudznam.com/booking/model}Comment" maxOccurs="unbounded"/>
 *         &lt;element name="favours" type="{http://www.otkudznam.com/booking/model}Favour" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lodgings",
    "imageUris",
    "lodgingTypes",
    "categories",
    "agents",
    "users",
    "comments",
    "favours"
})
@XmlRootElement(name = "getLodgingResponse")
public class GetLodgingResponse {

    @XmlElement(required = true)
    protected List<Lodging> lodgings;
    @XmlElement(required = true)
    protected List<ImageUrl> imageUris;
    @XmlElement(required = true)
    protected List<LodgingType> lodgingTypes;
    @XmlElement(required = true)
    protected List<Category> categories;
    @XmlElement(required = true)
    protected List<Agent> agents;
    @XmlElement(required = true)
    protected List<User> users;
    @XmlElement(required = true)
    protected List<Comment> comments;
    @XmlElement(required = true)
    protected List<Favour> favours;

    /**
     * Gets the value of the lodgings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lodgings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLodgings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Lodging }
     * 
     * 
     */
    public List<Lodging> getLodgings() {
        if (lodgings == null) {
            lodgings = new ArrayList<Lodging>();
        }
        return this.lodgings;
    }

    /**
     * Gets the value of the imageUris property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the imageUris property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImageUris().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ImageUrl }
     * 
     * 
     */
    public List<ImageUrl> getImageUris() {
        if (imageUris == null) {
            imageUris = new ArrayList<ImageUrl>();
        }
        return this.imageUris;
    }

    /**
     * Gets the value of the lodgingTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lodgingTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLodgingTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LodgingType }
     * 
     * 
     */
    public List<LodgingType> getLodgingTypes() {
        if (lodgingTypes == null) {
            lodgingTypes = new ArrayList<LodgingType>();
        }
        return this.lodgingTypes;
    }

    /**
     * Gets the value of the categories property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categories property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategories().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Category }
     * 
     * 
     */
    public List<Category> getCategories() {
        if (categories == null) {
            categories = new ArrayList<Category>();
        }
        return this.categories;
    }

    /**
     * Gets the value of the agents property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agents property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgents().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Agent }
     * 
     * 
     */
    public List<Agent> getAgents() {
        if (agents == null) {
            agents = new ArrayList<Agent>();
        }
        return this.agents;
    }

    /**
     * Gets the value of the users property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the users property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link User }
     * 
     * 
     */
    public List<User> getUsers() {
        if (users == null) {
            users = new ArrayList<User>();
        }
        return this.users;
    }

    /**
     * Gets the value of the comments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Comment }
     * 
     * 
     */
    public List<Comment> getComments() {
        if (comments == null) {
            comments = new ArrayList<Comment>();
        }
        return this.comments;
    }

    /**
     * Gets the value of the favours property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the favours property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFavours().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Favour }
     * 
     * 
     */
    public List<Favour> getFavours() {
        if (favours == null) {
            favours = new ArrayList<Favour>();
        }
        return this.favours;
    }

}
