//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.14 at 07:13:31 PM CEST 
//


package com.otkudznam.booking.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.booking.sys package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.booking.sys
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetLodgingRequest }
     * 
     */
    public GetLodgingRequest createGetLodgingRequest() {
        return new GetLodgingRequest();
    }

    /**
     * Create an instance of {@link Lodging }
     * 
     */
    public Lodging createLodging() {
        return new Lodging();
    }

    /**
     * Create an instance of {@link GetLodgingResponse }
     * 
     */
    public GetLodgingResponse createGetLodgingResponse() {
        return new GetLodgingResponse();
    }

    /**
     * Create an instance of {@link Favour }
     * 
     */
    public Favour createFavour() {
        return new Favour();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link ImageUrl }
     * 
     */
    public ImageUrl createImageUrl() {
        return new ImageUrl();
    }

    /**
     * Create an instance of {@link LodgingType }
     * 
     */
    public LodgingType createLodgingType() {
        return new LodgingType();
    }

}
