//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.21 at 09:18:56 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.booking.com/sys", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.otkudznam.booking.model;
