//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.04 at 05:18:36 AM CEST 
//


package com.booking.sys;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lodging" type="{http://www.booking.com/sys}Lodging" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="agent" type="{http://www.booking.com/sys}Agent"/>
 *         &lt;element name="favours" type="{http://www.booking.com/sys}Favour" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="lodgingTypes" type="{http://www.booking.com/sys}LodgingType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="categories" type="{http://www.booking.com/sys}Category" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reservations" type="{http://www.booking.com/sys}Reservations" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="comments" type="{http://www.booking.com/sys}Comment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="messages" type="{http://www.booking.com/sys}Message" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lodging",
    "agent",
    "favours",
    "lodgingTypes",
    "categories",
    "reservations",
    "comments",
    "messages"
})
@XmlRootElement(name = "getAllResponse")
public class GetAllResponse {

    protected List<Lodging> lodging;
    @XmlElement(required = true)
    protected Agent agent;
    protected List<Favour> favours;
    protected List<LodgingType> lodgingTypes;
    protected List<Category> categories;
    protected List<Reservations> reservations;
    protected List<Comment> comments;
    protected List<Message> messages;

    /**
     * Gets the value of the lodging property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lodging property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLodging().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Lodging }
     * 
     * 
     */
    public List<Lodging> getLodging() {
        if (lodging == null) {
            lodging = new ArrayList<Lodging>();
        }
        return this.lodging;
    }

    /**
     * Gets the value of the agent property.
     * 
     * @return
     *     possible object is
     *     {@link Agent }
     *     
     */
    public Agent getAgent() {
        return agent;
    }

    /**
     * Sets the value of the agent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Agent }
     *     
     */
    public void setAgent(Agent value) {
        this.agent = value;
    }

    /**
     * Gets the value of the favours property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the favours property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFavours().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Favour }
     * 
     * 
     */
    public List<Favour> getFavours() {
        if (favours == null) {
            favours = new ArrayList<Favour>();
        }
        return this.favours;
    }

    /**
     * Gets the value of the lodgingTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lodgingTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLodgingTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LodgingType }
     * 
     * 
     */
    public List<LodgingType> getLodgingTypes() {
        if (lodgingTypes == null) {
            lodgingTypes = new ArrayList<LodgingType>();
        }
        return this.lodgingTypes;
    }

    /**
     * Gets the value of the categories property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categories property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategories().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Category }
     * 
     * 
     */
    public List<Category> getCategories() {
        if (categories == null) {
            categories = new ArrayList<Category>();
        }
        return this.categories;
    }

    /**
     * Gets the value of the reservations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reservations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReservations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Reservations }
     * 
     * 
     */
    public List<Reservations> getReservations() {
        if (reservations == null) {
            reservations = new ArrayList<Reservations>();
        }
        return this.reservations;
    }

    /**
     * Gets the value of the comments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Comment }
     * 
     * 
     */
    public List<Comment> getComments() {
        if (comments == null) {
            comments = new ArrayList<Comment>();
        }
        return this.comments;
    }

    /**
     * Gets the value of the messages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Message }
     * 
     * 
     */
    public List<Message> getMessages() {
        if (messages == null) {
            messages = new ArrayList<Message>();
        }
        return this.messages;
    }

}
